import { ingredient, step, type Recipe } from './recipe';

// The 12 starter dinners carried over from Quick Kitchen. They ship with the app
// and are never synced; recipes the user adds live in the local database.
export const STARTER_RECIPES: readonly Recipe[] = [
  {
    id: 'starter-noodles',
    name: 'Sticky sesame chicken noodles',
    shortName: 'Noodles',
    minutes: 15,
    serves: 2,
    vegetarian: false,
    blurb: 'One pan, soy and honey glaze, ready in about 15 minutes.',
    oven: null,
    ingredients: [
      ingredient(300, 'g', 'chicken breast, sliced into thin strips'),
      ingredient(1, 'tbsp', 'vegetable oil'),
      ingredient(2, '', 'garlic cloves, crushed'),
      ingredient(1, 'tsp', 'ginger purée'),
      ingredient(300, 'g', 'frozen stir-fry veg'),
      ingredient(300, 'g', 'straight-to-wok noodles'),
      ingredient(3, 'tbsp', 'soy sauce'),
      ingredient(1.5, 'tbsp', 'honey'),
      ingredient(1, 'tsp', 'sesame oil'),
      ingredient(1, 'tbsp', 'sesame seeds'),
      ingredient(2, '', 'spring onions, sliced'),
    ],
    steps: [
      step('Mix the sauce', 'Stir the soy sauce, honey and sesame oil together in a small bowl.'),
      step(
        'Brown the chicken',
        'Heat the vegetable oil in a large frying pan or wok over a high heat. Fry the chicken until golden and cooked through, stirring now and then.',
        360,
      ),
      step(
        'Add aromatics and veg',
        'Stir in the garlic and ginger purée for 30 seconds, then add the frozen veg and cook until piping hot.',
        240,
      ),
      step(
        'Noodles and sauce',
        'Add the noodles and the sauce. Toss over the heat until the noodles are hot and the sauce turns sticky and glossy.',
        180,
      ),
      step('Finish', 'Scatter over the sesame seeds and spring onions and serve from the pan.'),
    ],
    note: 'Slice the chicken thinly so it cooks fast. Add a squeeze of lime or a pinch of chilli flakes for a kick. If the pan looks dry when the noodles go in, add a splash of water.',
  },
  {
    id: 'starter-pasta',
    name: 'Chorizo and butter bean tomato pasta',
    shortName: 'Pasta',
    minutes: 20,
    serves: 2,
    vegetarian: false,
    blurb: 'Chorizo oil does the flavouring. Sauce and pasta finish together.',
    oven: null,
    ingredients: [
      ingredient(180, 'g', 'dried pasta (penne or fusilli)'),
      ingredient(100, 'g', 'cooking chorizo, sliced'),
      ingredient(1, '', 'garlic clove, crushed'),
      ingredient(1, '', 'tin chopped tomatoes (400 g)'),
      ingredient(1, '', 'tin butter beans (400 g), drained'),
      ingredient(100, 'g', 'baby spinach'),
      ingredient(25, 'g', 'parmesan, grated'),
    ],
    steps: [
      step(
        'Start the pasta',
        'Cook the pasta in well-salted boiling water to the pack timing. Save a mugful of the cooking water before draining.',
        600,
      ),
      step(
        'Fry the chorizo',
        'In a large frying pan over a medium-high heat, fry the chorizo until it turns crisp at the edges and releases its red oil. Add the garlic for the last 30 seconds.',
        180,
      ),
      step(
        'Simmer the sauce',
        'Add the tomatoes and butter beans. Simmer, stirring now and then, until the sauce thickens a little.',
        480,
      ),
      step(
        'Bring it together',
        'Stir the spinach into the sauce until wilted. Add the drained pasta with a splash of the cooking water, then finish with the parmesan.',
      ),
    ],
    note: 'Put the pasta on first. The sauce takes about as long as the pasta does.',
  },
  {
    id: 'starter-gnocchi',
    name: 'Gnocchi with sausage and peppers',
    shortName: 'Gnocchi',
    minutes: 20,
    serves: 2,
    vegetarian: false,
    blurb: 'Shelf-stable gnocchi fries straight from the pack. No boiling.',
    oven: null,
    ingredients: [
      ingredient(4, '', 'pork sausages'),
      ingredient(1, 'tbsp', 'olive oil'),
      ingredient(1, '', 'red pepper, sliced'),
      ingredient(400, 'g', 'shelf-stable gnocchi'),
      ingredient(1, 'tbsp', 'pesto'),
      ingredient(20, 'g', 'parmesan or cheddar, grated (optional)'),
    ],
    steps: [
      step(
        'Brown the sausage meat',
        'Squeeze the sausage meat out of the skins into a large frying pan with the olive oil. Break it up with a spoon and fry until browned.',
        360,
      ),
      step('Add the pepper', 'Add the sliced pepper and fry until it softens.', 240),
      step(
        'Crisp the gnocchi',
        'Add the gnocchi straight from the packet. Fry, turning now and then, until golden in places.',
        360,
      ),
      step(
        'Finish',
        'Take the pan off the heat and stir through the pesto. Top with grated cheese if using.',
      ),
    ],
    note: 'Shelf-stable gnocchi is in the ambient aisle, usually near the pasta.',
  },
  {
    id: 'starter-halloumi',
    name: 'Halloumi and veg traybake',
    shortName: 'Traybake',
    minutes: 20,
    serves: 2,
    vegetarian: true,
    blurb: 'Chop, toss, roast. Couscous while it cooks.',
    oven: { celsius: 200, fanCelsius: 180, gasMark: '6' },
    ingredients: [
      ingredient(225, 'g', 'halloumi, cubed'),
      ingredient(1, '', 'courgette, cut into chunks'),
      ingredient(250, 'g', 'cherry tomatoes'),
      ingredient(1, '', 'red onion, cut into wedges'),
      ingredient(2, 'tbsp', 'olive oil'),
      ingredient(1, 'tsp', 'dried oregano'),
      ingredient(150, 'g', 'couscous'),
      ingredient(200, 'ml', 'boiling water or stock'),
      ingredient(0.5, '', 'lemon, to squeeze'),
    ],
    steps: [
      step('Heat the oven', 'Heat the oven to 200°C (180°C fan, gas 6) while you chop.'),
      step(
        'Load the tray',
        'Toss the halloumi, courgette, tomatoes and onion on a large baking tray with the olive oil and oregano. Spread everything out in one layer.',
      ),
      step('Roast', 'Roast, turning everything once halfway, until the halloumi is golden.', 900),
      step(
        'Couscous',
        'With about 5 minutes of roasting left, tip the couscous into a bowl and pour over the boiling water. Cover and leave, then fluff with a fork.',
        300,
      ),
      step('Serve', 'Spoon the traybake over the couscous and squeeze over the lemon.'),
    ],
    note: 'Preheat the oven before you start chopping, so the tray goes straight in.',
  },
  {
    id: 'starter-prawn',
    name: 'Garlic chilli prawn linguine',
    shortName: 'Linguine',
    minutes: 15,
    serves: 2,
    vegetarian: false,
    blurb: 'Pantry pasta with a fast, garlicky prawn sauce.',
    oven: null,
    ingredients: [
      ingredient(180, 'g', 'linguine'),
      ingredient(2, 'tbsp', 'olive oil'),
      ingredient(3, '', 'garlic cloves, thinly sliced'),
      ingredient(0.5, 'tsp', 'chilli flakes'),
      ingredient(200, 'g', 'raw king prawns'),
      ingredient(150, 'g', 'cherry tomatoes, halved'),
      ingredient(1, '', 'lemon, zested and juiced'),
      ingredient(10, 'g', 'flat-leaf parsley, chopped'),
    ],
    steps: [
      step(
        'Boil the pasta',
        'Cook the linguine in well-salted boiling water to the pack timing. Save a mugful of the cooking water before draining.',
        600,
      ),
      step(
        'Fry the garlic',
        'While the pasta cooks, warm the olive oil in a large frying pan over a medium heat. Fry the garlic and chilli flakes for 30 seconds until fragrant, without letting the garlic brown.',
      ),
      step(
        'Cook the prawns',
        'Add the prawns and cherry tomatoes. Cook, stirring now and then, until the prawns turn pink and the tomatoes begin to burst.',
        240,
      ),
      step(
        'Toss and serve',
        'Add the drained linguine to the pan with a splash of the cooking water and the lemon zest, then squeeze in some of the juice. Toss until glossy and scatter over the parsley.',
      ),
    ],
    note: 'Cooked prawns also work. Add them in the last minute so they only warm through. Defrost frozen prawns fully first.',
  },
  {
    id: 'starter-mushroom',
    name: 'Creamy mushroom and spinach tagliatelle',
    shortName: 'Tagliatelle',
    minutes: 20,
    serves: 2,
    vegetarian: true,
    blurb: 'Golden mushrooms in a quick garlic cream sauce.',
    oven: null,
    ingredients: [
      ingredient(200, 'g', 'tagliatelle'),
      ingredient(1, 'tbsp', 'olive oil'),
      ingredient(15, 'g', 'butter'),
      ingredient(250, 'g', 'chestnut mushrooms, sliced'),
      ingredient(2, '', 'garlic cloves, crushed'),
      ingredient(100, 'ml', 'double cream'),
      ingredient(100, 'g', 'baby spinach'),
      ingredient(25, 'g', 'vegetarian hard cheese, grated'),
      ingredient(null, '', 'salt and black pepper'),
    ],
    steps: [
      step(
        'Boil the pasta',
        'Cook the tagliatelle in well-salted boiling water to the pack timing. Save a mugful of the cooking water before draining.',
        600,
      ),
      step(
        'Brown the mushrooms',
        'Heat the olive oil and butter in a large frying pan over a high heat. Fry the mushrooms, stirring only now and then, until golden and the liquid has cooked off.',
        360,
      ),
      step(
        'Make the sauce',
        'Stir in the garlic for 30 seconds, then pour in the cream with a splash of the cooking water. Simmer until slightly thickened.',
        120,
      ),
      step(
        'Bring it together',
        'Stir in the spinach until wilted, then add the drained pasta and most of the cheese. Season, loosen with more cooking water if needed and top with the rest of the cheese.',
      ),
    ],
    note: 'Do not stir the mushrooms too often. Leaving them alone is what browns them.',
  },
  {
    id: 'starter-friedrice',
    name: 'Egg fried rice with peas',
    shortName: 'Fried rice',
    minutes: 15,
    serves: 2,
    vegetarian: true,
    blurb: 'Pouch rice, eggs and frozen peas, all in one pan.',
    oven: null,
    ingredients: [
      ingredient(250, 'g', 'microwave basmati or long-grain rice (1 pouch)'),
      ingredient(1, 'tbsp', 'vegetable oil, split'),
      ingredient(3, '', 'eggs, beaten'),
      ingredient(3, '', 'spring onions, sliced'),
      ingredient(1, '', 'garlic clove, crushed'),
      ingredient(100, 'g', 'frozen peas'),
      ingredient(2, 'tbsp', 'soy sauce'),
      ingredient(1, 'tsp', 'sesame oil'),
    ],
    steps: [
      step(
        'Loosen the rice',
        'Squeeze the rice pouch to break up the grains before the rice goes in the pan.',
      ),
      step(
        'Scramble the eggs',
        'Heat half the vegetable oil in a large frying pan or wok over a high heat. Pour in the eggs and stir until just set, then tip onto a plate.',
        90,
      ),
      step(
        'Fry the rice',
        'Add the rest of the oil, then the white parts of the spring onions and the garlic for 30 seconds. Add the rice and peas and stir-fry until piping hot and starting to crisp.',
        240,
      ),
      step(
        'Finish',
        'Return the eggs to the pan with the soy sauce and sesame oil. Toss together and scatter over the green parts of the spring onions.',
      ),
    ],
    note: 'Cold leftover rice gives the best texture. If you use a fresh pouch, spread it out for a few minutes first.',
  },
  {
    id: 'starter-shakshuka',
    name: 'Shakshuka',
    shortName: 'Shakshuka',
    minutes: 20,
    serves: 2,
    vegetarian: true,
    blurb: 'Eggs poached in a spiced tomato and pepper sauce.',
    oven: null,
    ingredients: [
      ingredient(1, 'tbsp', 'olive oil'),
      ingredient(1, '', 'onion, sliced'),
      ingredient(1, '', 'red pepper, sliced'),
      ingredient(2, '', 'garlic cloves, crushed'),
      ingredient(1, 'tsp', 'ground cumin'),
      ingredient(1, 'tsp', 'smoked paprika'),
      ingredient(1, '', 'tin chopped tomatoes (400 g)'),
      ingredient(4, '', 'eggs'),
      ingredient(50, 'g', 'feta, crumbled'),
      ingredient(null, '', 'bread, to serve'),
    ],
    steps: [
      step(
        'Soften the veg',
        'Warm the olive oil in a large, deep frying pan over a medium heat. Fry the onion and pepper until soft.',
        300,
      ),
      step(
        'Add spices and tomatoes',
        'Stir in the garlic, cumin and smoked paprika for 1 minute. Add the tomatoes, season and simmer until thickened.',
        300,
      ),
      step(
        'Poach the eggs',
        'Make four hollows in the sauce and crack an egg into each. Cover with a lid or foil and cook until the whites are set and the yolks are still soft.',
        360,
      ),
      step('Serve', 'Scatter over the feta and serve from the pan with bread.'),
    ],
    note: 'Use a lid that fits, as the steam sets the tops of the eggs. Check after 4 minutes if you like runny yolks.',
  },
  {
    id: 'starter-chickpea',
    name: 'Chickpea and spinach curry',
    shortName: 'Curry',
    minutes: 20,
    serves: 2,
    vegetarian: true,
    blurb: 'Store-cupboard curry with coconut milk and a spoonful of paste.',
    oven: null,
    ingredients: [
      ingredient(1, 'tbsp', 'vegetable oil'),
      ingredient(1, '', 'onion, finely chopped'),
      ingredient(2, '', 'garlic cloves, crushed'),
      ingredient(1, 'tsp', 'ginger purée'),
      ingredient(2, 'tbsp', 'medium curry paste'),
      ingredient(1, '', 'tin chopped tomatoes (400 g)'),
      ingredient(1, '', 'tin chickpeas (400 g), drained'),
      ingredient(200, 'ml', 'coconut milk'),
      ingredient(100, 'g', 'baby spinach'),
      ingredient(250, 'g', 'microwave basmati rice (1 pouch)'),
    ],
    steps: [
      step(
        'Soften the onion',
        'Heat the oil in a large saucepan over a medium heat. Fry the onion until soft and starting to colour.',
        300,
      ),
      step(
        'Fry the paste',
        'Stir in the garlic, ginger purée and curry paste and cook for 1 minute, stirring so the paste does not catch.',
        60,
      ),
      step(
        'Simmer',
        'Add the tomatoes, chickpeas and coconut milk. Bring to a simmer and cook until the sauce thickens.',
        600,
      ),
      step(
        'Spinach and rice',
        'Stir in the spinach until wilted. Heat the rice following the pack instructions and serve the curry over it.',
      ),
    ],
    note: 'Keep the rest of the coconut milk in a covered tub in the fridge and use it within a few days.',
  },
  {
    id: 'starter-salmon',
    name: 'Honey soy salmon traybake',
    shortName: 'Salmon',
    minutes: 20,
    serves: 2,
    vegetarian: false,
    blurb: 'Glazed salmon and tenderstem on one tray, with pouch rice.',
    oven: { celsius: 200, fanCelsius: 180, gasMark: '6' },
    ingredients: [
      ingredient(2, '', 'salmon fillets'),
      ingredient(200, 'g', 'tenderstem broccoli'),
      ingredient(1, 'tbsp', 'vegetable oil'),
      ingredient(2, 'tbsp', 'soy sauce'),
      ingredient(1, 'tbsp', 'honey'),
      ingredient(1, '', 'garlic clove, crushed'),
      ingredient(1, 'tsp', 'ginger purée'),
      ingredient(1, 'tsp', 'sesame oil'),
      ingredient(250, 'g', 'microwave rice (1 pouch)'),
      ingredient(1, 'tsp', 'sesame seeds'),
    ],
    steps: [
      step('Heat the oven', 'Heat the oven to 200°C (180°C fan, gas 6).'),
      step(
        'Make the glaze',
        'Stir the soy sauce, honey, garlic, ginger purée and sesame oil together in a small bowl.',
      ),
      step(
        'Load the tray',
        'Toss the broccoli with the vegetable oil on a large baking tray and push it to the sides. Put the salmon in the middle, skin-side down, and spoon the glaze over the fish.',
      ),
      step(
        'Roast',
        'Roast until the salmon flakes easily and the broccoli is tender with crisp tips.',
        780,
      ),
      step(
        'Rice and serve',
        'With 2 minutes of roasting left, heat the rice following the pack instructions. Serve the salmon and broccoli over the rice, spooning over the juices from the tray, and scatter with sesame seeds.',
      ),
    ],
    note: 'Thick fillets may need a few extra minutes. The salmon is done when it flakes and is opaque all the way through.',
  },
  {
    id: 'starter-flatbread',
    name: 'Flatbread pizzas',
    shortName: 'Pizzas',
    minutes: 15,
    serves: 2,
    vegetarian: false,
    blurb: 'Naan or flatbread bases on a hot tray for a crisp underside.',
    oven: { celsius: 220, fanCelsius: 200, gasMark: '7' },
    ingredients: [
      ingredient(2, '', 'large flatbreads or naan'),
      ingredient(4, 'tbsp', 'tomato passata or pizza sauce'),
      ingredient(125, 'g', 'mozzarella, torn'),
      ingredient(100, 'g', 'toppings of your choice (sliced peppers, mushrooms, pepperoni)'),
      ingredient(1, 'tsp', 'dried oregano'),
      ingredient(1, 'tbsp', 'olive oil'),
    ],
    steps: [
      step(
        'Heat the oven',
        'Heat the oven to 220°C (200°C fan, gas 7) with a baking tray inside so it gets hot.',
      ),
      step(
        'Build the pizzas',
        'Spread the passata over the flatbreads, leaving a small border. Scatter over the mozzarella and toppings, then sprinkle with oregano.',
      ),
      step(
        'Bake',
        'Lay each pizza on a sheet of baking paper, slide them onto the hot tray and bake until the edges are crisp and the cheese is bubbling.',
        540,
      ),
      step('Finish', 'Drizzle with the olive oil and serve straight away.'),
    ],
    note: 'Keep toppings thin so they cook through in the time. Pre-cook anything raw and thick, such as sausage.',
  },
  {
    id: 'starter-pesto',
    name: 'Pesto chicken and tomato bake',
    shortName: 'Pesto chicken',
    minutes: 20,
    serves: 2,
    vegetarian: false,
    blurb: 'Thin chicken fillets under pesto and mozzarella, with couscous.',
    oven: { celsius: 200, fanCelsius: 180, gasMark: '6' },
    ingredients: [
      ingredient(2, '', 'chicken breasts, each sliced in half horizontally into thin fillets'),
      ingredient(3, 'tbsp', 'green pesto'),
      ingredient(200, 'g', 'cherry tomatoes'),
      ingredient(1, 'tbsp', 'olive oil'),
      ingredient(125, 'g', 'mozzarella, torn'),
      ingredient(150, 'g', 'couscous'),
      ingredient(200, 'ml', 'boiling water or stock'),
    ],
    steps: [
      step('Heat the oven', 'Heat the oven to 200°C (180°C fan, gas 6).'),
      step(
        'Load the tray',
        'Put the thin chicken fillets and cherry tomatoes on a large baking tray. Drizzle the tomatoes with the olive oil, season, then spoon the pesto over the chicken.',
      ),
      step('First bake', 'Roast until the chicken is nearly cooked through.', 600),
      step(
        'Add the cheese',
        'Scatter the mozzarella over the chicken and return to the oven until the cheese is melted and golden and the chicken is cooked through.',
        300,
      ),
      step(
        'Couscous',
        'While the cheese melts, put the couscous in a bowl and pour over the boiling water. Cover and leave to soak, then fluff with a fork. Serve the chicken and tomatoes on top.',
        300,
      ),
    ],
    note: 'Check the thickest piece of chicken. It must be white all the way through with no pink, and the juices should run clear.',
  },
];
